name: Deploy MkDocs site

on:
  push:
    branches:
      - main   # change if your default branch is different

permissions:
  contents: write   # <-- allows pushing to gh-pages

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install mkdocs-material

      - name: Configure git identity
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Build and deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}   # <-- provide token to mkdocs/ghp-import
        run: |
          mkdocs gh-deploy --force --remote-name origin --remote-branch gh-pages
